name: Deploy Development

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%F_%H-%M')"

      - name: Rename files
        run: |
          mkdir out
          cp resume.pdf "out/Galen-Guyer-Resume-dev.pdf"
          cp resume.pdf "out/Galen-Guyer-Resume-dev-${{ steps.date.outputs.date }}.pdf"

      - name: Upload to R2
        uses: elementemerald/r2-upload-action@v1.1.2
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: out/
