name: Publish Resume

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Set vars
        run: |
          echo "DATE=$(date +'%F_%H-%M')" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true

      - name: Rename files
        run: |
          mkdir out
          cp resume.pdf "out/Galen-Guyer-Resume-${{ github.ref_name }}.pdf"
          cp resume.pdf "out/Galen-Guyer-Resume-${SHORT_SHA}.pdf"
          cp resume.pdf "out/Galen-Guyer-Resume-${DATE}.pdf"

      - name: Rename files (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cp resume.pdf "out/Galen-Guyer-Resume.pdf"

      - name: Upload to R2
        uses: elementemerald/r2-upload-action@v1.1.2
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: out/
          destination-dir: resume/
